MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "11"                   # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "11"                   # [osx]
c_compiler_version:        # [osx]
 - '12'                    # [osx]
cxx_compiler_version:      # [osx]
 - '12'                    # [osx]
