{% set version = "4.2.1" %}
{% set variant = "openblas" %}

package:
  name: octave
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 80c28f6398576b50faca0e602defb9598d6f7308b0903724442c2a35a605333b
  patches:
    # patches taken from macports
    # https://github.com/macports/macports-ports/tree/master/math/octave/files
    # Link fails with undefined symbol ~file_stat
    - patch-file-stat.cc.diff
    # qscintilla2 library is not found without this
    - patch-qscintilla2.diff

build:
  number: 9
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - sed
    - perl
    - pkg-config  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('expat') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxt') }}  # [linux]
    - {{ cdt('libxft') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - openblas
    - blas 1.1 {{ variant }}
    - pcre
    - readline
    - arpack
    - curl
    - fftw
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - suitesparse
    - zlib
    - bzip2
    - portaudio
    - libsndfile
    - qscintilla2
    - qhull
    - graphicsmagick   # [linux]
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl
  run:
    - openblas
    - blas 1.1 {{ variant }}
    - pcre
    - readline
    - arpack
    - curl
    - {{ pin_compatible("fftw", max_pin="x.x") }}
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - {{ pin_compatible("suitesparse", max_pin="x.x") }}
    - zlib
    - bzip2
    - {{ pin_compatible("portaudio") }}
    - libsndfile
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qhull
    - {{ pin_compatible("graphicsmagick") }}   # [linux]
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl

test:
  commands:
    - octave --version

about:
  home: https://www.gnu.org/software/octave/
  license: GPLv3
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: 'GNU Octave is a high-level language, primarily intended for numerical computations'

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
