{% set version = "4.2.1" %}
{% set variant = "openblas" %}

package:
  name: octave
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 80c28f6398576b50faca0e602defb9598d6f7308b0903724442c2a35a605333b
  patches:
    # patches taken from macports
    # https://github.com/macports/macports-ports/tree/master/math/octave/files
    # Link fails with undefined symbol ~file_stat
    - patch-file-stat.cc.diff
    # qscintilla2 library is not found without this
    - patch-qscintilla2.diff

build:
  number: 6
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - perl 5.20.3.1
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sed
    - openblas
    - blas 1.1 {{ variant }}
    - pcre 8.37
    - readline
    - arpack
    - curl
    - fftw 3.3.*
    - fontconfig
    - freetype
    - glpk
    - gnuplot 5.2.*
    - hdf5
    - suitesparse 4.5.*
    - zlib
    - bzip2
    - portaudio 19
    - libsndfile 1.0.27
    - qscintilla2 2.9.*
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl
  run:
    - openblas
    - blas 1.1 {{ variant }}
    - pcre >=8.37,<9
    - readline
    - arpack
    - curl
    - fftw 3.3.*
    - fontconfig
    - freetype
    - glpk
    - gnuplot 5.2.*
    - hdf5
    - suitesparse 4.5.*
    - zlib
    - bzip2
    - portaudio 19
    - libsndfile >=1.0.27,<1.1
    - qscintilla2 2.9.*
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl

test:
  commands:
    - octave --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://www.gnu.org/software/octave/
  license: GPLv3
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: 'GNU Octave is a high-level language, primarily intended for numerical computations'

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
