{% set version = "4.2.1" %}
{% set variant = "openblas" %}

package:
  name: octave
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 80c28f6398576b50faca0e602defb9598d6f7308b0903724442c2a35a605333b
  patches:
    # patches taken from macports
    # https://github.com/macports/macports-ports/tree/master/math/octave/files
    # Link fails with undefined symbol ~file_stat
    - patch-file-stat.cc.diff
    # qscintilla2 library is not found without this
    - patch-qscintilla2.diff

build:
  number: 6
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - gcc          # [osx]
    - sed
    - perl 5.20.3.1
    - openblas 0.2.20|0.2.20.*
    - blas 1.1 {{ variant }}
    - pcre 8.37
    - readline 7.0
    - arpack 3.5.*
    - curl >=7.44.0,<8
    - fftw 3.3.*
    - fontconfig 2.12.*
    - freetype 2.8.1
    - glpk 4.61|4.62
    - gnuplot 5.2.*
    - hdf5 1.10.1
    - suitesparse 4.5.*
    - zlib 1.2.11
    - bzip2 1.0.*
    - portaudio 19
    - libsndfile 1.0.27
    - qscintilla2 2.9.*
    # Following gets linked at the end.
    - icu 58.*
    - ncurses 5.9
    - xz 5.2.*
    - libxml2 2.9.*
    - libpng >=1.6.32,<1.6.35
    - glib 2.55.*
    - qt 5.6.*
    - openssl 1.0.*
  run:
    - openblas 0.2.20|0.2.20.*
    - blas 1.1 {{ variant }}
    - pcre >=8.37,<9
    - readline 7.0
    - arpack 3.5.*
    - curl >=7.44.0,<8
    - fftw 3.3.*
    - fontconfig 2.12.*
    - freetype 2.8.1
    - glpk 4.61|4.62
    - gnuplot 5.2.*
    - hdf5 1.10.1
    - suitesparse 4.5.*
    - zlib 1.2.11
    - bzip2 1.0.*
    - portaudio 19
    - libsndfile >=1.0.27,<1.1
    - qscintilla2 2.9.*
    # Following gets linked at the end.
    - icu 58.*
    - ncurses 5.9
    - xz 5.2.*
    - libxml2 2.9.*
    - libpng >=1.6.32,<1.6.35
    - glib 2.55.*
    - qt 5.6.*
    - openssl 1.0.*
    - libgfortran    # [osx]

test:
  commands:
    - octave --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://www.gnu.org/software/octave/
  license: GPLv3
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: 'GNU Octave is a high-level language, primarily intended for numerical computations'

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
