{% set version = "10.2.0" %}

package:
  name: octave
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 07fb6d9339d2f350735c91671be8e874d160018cc6b688f9efd9d558d237f69f

build:
  number: 0
  skip: true  # [win]
  binary_has_prefix_files:   # [linux]
    - bin/octave-{{ version }}  # [linux]
  run_exports:
    - {{ pin_subpackage('octave', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - automake
    - sed
    - perl
    - ghostscript
    - pkg-config  # [not win]
    - libgomp     # [linux]
    - llvm-openmp  # [osx]
    - bison
    - gperf
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libglu  # [linux]
    - pcre
    - ghostscript
    - pkg-config
    - sundials
    - readline
    - arpack
    - curl
    - libcurl
    - fftw
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - suitesparse
    - zlib
    - bzip2
    - portaudio
    - libsndfile
    - qscintilla2
    - qhull
    - graphicsmagick
    - mkl  # [linux64]
    # Following gets linked at the end.
    - icu
    - ncurses
    - liblzma-devel
    - libxml2
    - libpng
    - glib
    - qt-main
    - openssl
    - texinfo
    - gl2ps
    - fltk
    - libiconv !=1.18
    - alsa-lib  # [linux]
    - rapidjson
    - xorg-libxrender  # [linux]
    - xorg-libxfixes   # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxfixes   # [linux]
  run:
    - ghostscript
    - texinfo
    - gl2ps
    - libglu  # [linux]
    - fltk
    - pcre
    - readline
    - arpack
    - curl
    - sundials
    - {{ pin_compatible("fftw", max_pin="x.x") }}
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - {{ pin_compatible("suitesparse", max_pin="x.x") }}
    - zlib
    - bzip2
    - {{ pin_compatible("portaudio") }}
    - libsndfile
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qhull
    - {{ pin_compatible("graphicsmagick") }}
    - mkl  # [linux64]
    # Following gets linked at the end.
    - icu
    - ncurses
    - liblzma-devel
    - libxml2
    - libpng
    - glib
    - qt-main
    - openssl

test:
  requires:
    - coreutils
  commands:
    - octave --version
    - touch test_file.txt
    - octave test_file.txt
    - octave --eval "imwrite(uint8(rand(20,20,3).*255),'test.jpg')"
    - octave --eval "help pkg"
    - octave --eval "path"

about:
  home: https://www.gnu.org/software/octave/
  license: GPL-3.0-or-later
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: GNU Octave is a high-level language, primarily intended for numerical computations

extra:
  recipe-maintainers:
    - SylvainCorlay
    - isuruf
    - ocefpaf
    - izahn
    - ngam
    - matthiasdiener
