context:
  version: "10.3.0"

package:
  name: octave
  version: ${{ version }}

source:
  url:
    - https://ftp.gnu.org/gnu/octave/octave-${{ version }}.tar.gz
    - https://ftpmirror.gnu.org/octave/octave-${{ version }}.tar.gz
  sha256: 2fcb38dc062e440f1e06c069bbca840ed46dcc8f983e473e1558fcc38384ee6b

build:
  number: 2
  skip:
    - if: win
      then: true

  prefix_detection:
    force_file_type:
      binary:
        - if: linux
          then:
            - bin/octave-${{ version }}


requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - make
    - automake
    - sed
    - perl
    - ghostscript
    - pkg-config
    - bison
    - gperf
    - if: linux
      then:
        - libgomp
        - ${{ cdt("mesa-libgl-devel") }}
        - ${{ cdt("mesa-dri-drivers") }}
        - ${{ cdt("libselinux") }}
        - ${{ cdt("xorg-x11-proto-devel") }}
    - if: osx
      then:
        - llvm-openmp

  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - pcre
    - ghostscript
    - pkg-config
    - sundials
    - readline
    - arpack
    - curl
    - libcurl
    - fftw
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - suitesparse
    - zlib
    - bzip2
    - portaudio
    - libsndfile
    - qscintilla2
    - qhull
    - graphicsmagick
    - icu
    - ncurses
    - liblzma-devel
    - libxml2-devel
    - libpng
    - glib
    - qt-main
    - openssl
    - texinfo
    - gl2ps
    - fltk
    - libiconv
    - rapidjson
    - if: linux
      then:
        - libglu
        - libgl-devel
        - alsa-lib
        - xorg-xorgproto
        - xorg-libxrender
        - xorg-libxfixes
        - xorg-libx11
        - xorg-libxext

  run:
    - ghostscript
    - texinfo
    - gl2ps
    - fltk
    - pcre
    - readline
    - arpack
    - curl
    - sundials
    - ${{ pin_compatible("fftw", upper_bound="x.x") }}
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - ${{ pin_compatible("suitesparse", upper_bound="x.x") }}
    - zlib
    - bzip2
    - ${{ pin_compatible("portaudio") }}
    - libsndfile
    - ${{ pin_compatible("qscintilla2", upper_bound="x.x") }}
    - qhull
    - ${{ pin_compatible("graphicsmagick") }}
    - icu
    - ncurses
    - liblzma-devel
    - libxml2-devel
    - libpng
    - glib
    - qt-main
    - openssl
    - if: linux
      then:
        - libglu

tests:
  - requirements:
     run:
      - coreutils
    script: |
      octave --version
      touch test_file.txt
      octave test_file.txt
      octave --eval "imwrite(uint8(rand(20,20,3).*255),'test.jpg')"
      octave --eval "help pkg"
      octave --eval "path"

about:
  homepage: https://www.gnu.org/software/octave/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: GNU Octave is a high-level language, primarily intended for numerical computations
  documentation: https://www.gnu.org/software/octave/doc/interpreter/

extra:
  recipe-maintainers:
    - IsabelParedes
    - SylvainCorlay
    - isuruf
    - ocefpaf
    - izahn
    - ngam
    - matthiasdiener
